;

CREATE TABLE PERSONEN(
    PERSID INT AUTO_INCREMENT,
    NAME VARCHAR(255),
    GESCHLECHT CHAR(1),
    EMAIL VARCHAR(255),
    HANDY VARCHAR(255),
    GEBURTSJAHR INT,
    VERFUEGBARKEIT INT,
	PRIMARY KEY(PERSID)
); 
    
CREATE TABLE GELEGENHEITEN(
    GELEGENID INT AUTO_INCREMENT,
    ORT VARCHAR(255),
    ART VARCHAR(255),
    ANZPLAETZE INT,
    PERSID INT NOT NULL,
    PID INT NOT NULL,
	PRIMARY KEY(GELEGENID)
);       
      
CREATE TABLE GAESTELISTE(
    PID INT NOT NULL,
    PERSID INT NOT NULL,
    KOMMT BOOLEAN,
	PRIMARY KEY(PID, PERSID)
);               

CREATE TABLE PARTY(
    PID INT AUTO_INCREMENT,
    NAME VARCHAR(255),
    ZEIT DATETIME,
    ORT VARCHAR(255),
    MOTTO VARCHAR(255),
	PRIMARY KEY(PID)
);             
         
CREATE TABLE GELEGEN_NUTZUNG(
    GELEGENID INT NOT NULL,
    PERSID INT NOT NULL,
	PRIMARY KEY(GELEGENID, PERSID)
);         

CREATE TABLE MATERIALTEMPLATE(
    MTID INT AUTO_INCREMENT,
    ART VARCHAR(255),
    NAME VARCHAR(255),
	PRIMARY KEY(MTID)
);              

CREATE TABLE MATERIAL(
    MID INT AUTO_INCREMENT,
    MTID INT NOT NULL,
    PID INT NOT NULL,
    PERSID INT NOT NULL,
    ANZAHL INT,
    EINHEIT VARCHAR(255),
    NOTIZ VARCHAR(511),
	PRIMARY KEY(MID)
);        
    
CREATE TABLE PUTZTEMPLATE(
    PTID INT AUTO_INCREMENT,
    ART VARCHAR(255),
	PRIMARY KEY(PTID)
);          
           
CREATE TABLE PUTZ(
    RID INT AUTO_INCREMENT,
    PTID INT NOT NULL,
    PID INT NOT NULL,
    RAUM VARCHAR(255),
    DAUER INT,
    NOTIZ VARCHAR(511),
	PRIMARY KEY(RID)
);          

CREATE TABLE PUTZ_PERSONEN(
    RID INT NOT NULL,
    PERSID INT NOT NULL,
	PRIMARY KEY(RID, PERSID)
); 

CREATE TABLE TASKKATEGORIE(
    KID INT AUTO_INCREMENT,
    KATEGORIE VARCHAR(255),
	PRIMARY KEY(KID)
);    

CREATE TABLE TASKS(
    TID INT AUTO_INCREMENT,
    NAME VARCHAR(255),
    STATUS INT,
    PID INT NOT NULL,
    KID INT NOT NULL,
	PRIMARY KEY(TID)
);  

ALTER TABLE PUTZ ADD FOREIGN KEY(PID) REFERENCES PARTY(PID);           
ALTER TABLE GELEGENHEITEN ADD FOREIGN KEY(PERSID) REFERENCES PERSONEN(PERSID);          
ALTER TABLE GELEGEN_NUTZUNG ADD FOREIGN KEY(GELEGENID) REFERENCES GELEGENHEITEN(GELEGENID);              
ALTER TABLE PUTZ_PERSONEN ADD FOREIGN KEY(RID) REFERENCES PUTZ(RID);    
ALTER TABLE PUTZ ADD FOREIGN KEY(PTID) REFERENCES PUTZTEMPLATE(PTID);   
ALTER TABLE MATERIAL ADD FOREIGN KEY(PID) REFERENCES PARTY(PID);      
ALTER TABLE TASKS ADD FOREIGN KEY(KID) REFERENCES TASKKATEGORIE(KID); 
ALTER TABLE GELEGENHEITEN ADD FOREIGN KEY(PID) REFERENCES PARTY(PID);  
ALTER TABLE MATERIAL ADD FOREIGN KEY(MTID) REFERENCES MATERIALTEMPLATE(MTID);          
ALTER TABLE MATERIAL ADD FOREIGN KEY(PERSID) REFERENCES PERSONEN(PERSID);            
ALTER TABLE TASKS ADD FOREIGN KEY(PID) REFERENCES PARTY(PID);        
ALTER TABLE GAESTELISTE ADD FOREIGN KEY(PERSID) REFERENCES PERSONEN(PERSID);            
ALTER TABLE PUTZ_PERSONEN ADD FOREIGN KEY(PERSID) REFERENCES PERSONEN(PERSID);         
ALTER TABLE GAESTELISTE ADD FOREIGN KEY(PID) REFERENCES PARTY(PID);      
ALTER TABLE GELEGEN_NUTZUNG ADD FOREIGN KEY(PERSID) REFERENCES PERSONEN(PERSID);

COMMIT;        
